name: ${project.name}
version: ${project.version}
api-version: 1.14
main: ${project.groupId}.${project.artifactId}.${project.name}
description: ${project.description}
authors: [drives_a_ford, SlimeDog]
load: STARTUP

commands:
  mobcolors:
    description: The main command
    usage: /<command> <args>
    aliases: [mc]
    permission: mobcolors.command
 
permissions:
  mobcolors.command:
    description: Allows using the main command
    default: op
  mobcolors.reload:
    description: Allows using the reload subcommand
    default: op
    children:
      mobcolors.command: true
  mobcolors.scan:
    description: Allows using the scan subcommand
    default: op
    children:
      mobcolors.command: true
  mobcolors.color:
    description: Allows using the color subcommand
    default: op
    children:
      mobcolors.command: true
  mobcolors.info:
    description: Allows using the info subcommand
    default: op
    children:
      mobcolors.command: true
